#!/usr/bin/env bash
Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

format="server {
    listen 80;
    server_name example.com;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

config="#comment \n\tserver {\n\tlisten 80;\n\tserver_name example.com;\n\n\tlocation /redirect_me {\n\t\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t}\n\t}"

sed -i "22 i ${config}" /etc/nginx/sites-enabled/default

service nginx restart
