#!/usr/bin/env bash
# Task 0 

HOST_NAME=$(hostname)

# Install nginx
apt-get update
apt-get install -y nginx

# Overwrite default index file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404_error.html

custom="
server {
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /404_error.html;
        location = /404_error.html {
            root /var/www/html;
            internal;
        }

    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;
    add_header X-Served-By ${HOST_NAME};


    location / {
        try_files \$uri \$uri/ =404;
    }
}
"
echo "${custom}" > /etc/nginx/sites-available/default

service nginx restart
