#!/usr/bin/env bash
#  compressed archive of a MySQL dump.
# today=$(date +"%d")
# month=$(date +"%m")
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
